version: "3.8"

volumes:
  postgres-data:
    driver: local

networks:
  my-network:
    external: true  # Подключаем к общей сети

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres-zoomcamp
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network  # Подключаем к общей сети
